### ISSUE TITLE
Add hlint configuration?

### ISSUE THREAD

**Issue by philderbeast** [nasa/ogma#95]
Linting was clean with #51 but now there are warnings:

```yaml
# Warnings currently triggered by your code
- ignore: {name: "Empty single-line comment"} # 49 hints
- ignore: {name: "Redundant bracket"} # 4 hints
- ignore: {name: "Use intercalate"} # 10 hints
- ignore: {name: "Use map once"} # 4 hints
- ignore: {name: "Use zipWith"} # 1 hint
```

How about adding configuration (and a gh-action?) to help maintain this project in a lint-clean state?

I've seen the [no-pull request](https://github.com/nasa/ogma#contributions) note. If you want to pick up the configuration, I've done it over on https://github.com/typechecker/ogma/commit/b42073e39657080eca81dda5d70b8b270f1a7426. The command for creating a default configuration is:

    hlint --default -j . > .hlint.yaml
